### ISSUE TITLE
Recursion error?

### ISSUE THREAD

**Issue by tdhopper** [pssdbt/flask-skeleton#5]
I noticed you were the one that asked this question: http://stackoverflow.com/questions/14330256/occasional-flask-server-error-runtimeerror-maximum-recursion-depth-exceeded-w.

I can't find anyone else having the same problem. I'm seeing this same issue with flask skeleton. Could it be something in your boilerplate? 

I will try to track it down if I find the energy.

**Comment by pssdbt** [comment]
It very well could be - I haven't taken a look at this one in a while though, I should really go in and update it one of these days! Did you dig in and find anything?
